"""Bulk seed for performance/caching benchmarks in local development."""

from __future__ import annotations

import argparse
import os
import random
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TRACKFLOW_API_ROOT = REPO_ROOT / "services" / "trackflow-api"
DEFAULT_SQLITE_PATH = REPO_ROOT / "data" / "inventory-performance.db"

if str(TRACKFLOW_API_ROOT) not in sys.path:
    sys.path.insert(0, str(TRACKFLOW_API_ROOT))

os.environ.setdefault("SUPABASE_URI", f"sqlite:///{DEFAULT_SQLITE_PATH.as_posix()}")
os.environ.setdefault("TRACKFLOW_DATABASE_PATH", str(REPO_ROOT / "data" / "app-performance.json"))

from sqlmodel import Session, select

from seed import run_seed
from trackflow_api.core.database import get_inventory_engine, init_db
from trackflow_api.domain.incidents.manager_config import load_manager_context
from trackflow_api.models import ExitType, SKU, SKUCategory, StockEntry, StockExit, WarehouseCode
from trackflow_api.repositories import incident_repository, supplier_repository


CLIENTS = ["ModaSprint", "ElectroHub", "FreshBox", "PureStep", "GlowLab", "UrbanWear"]
CATEGORIES = [SKUCategory.FASHION, SKUCategory.ELECTRONICS, SKUCategory.COSMETICS]
WAREHOUSES = [WarehouseCode.LA, WarehouseCode.ZGZ]
SUPPLIER_CATEGORIES = [
    "carrier_last_mile",
    "carrier_international",
    "warehouse_supplies",
    "packaging_materials",
    "reverse_logistics",
]
INCIDENT_STATUSES = ["open", "in_progress", "resolved"]
INCIDENT_CATEGORIES = ["lost_parcel", "damaged_goods", "delayed_delivery", "wrong_address"]
INCIDENT_ORIGINS = ["customer", "carrier", "warehouse"]
INCIDENT_BRANCHES = ["central", "la_hub", "zgz_hub"]


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Seed bulk data for caching benchmarks.")
    parser.add_argument("--products", type=int, default=500, help="Target SKU rows to ensure.")
    parser.add_argument("--movements", type=int, default=5000, help="Target stock movement rows.")
    parser.add_argument("--suppliers", type=int, default=200, help="Target supplier rows.")
    parser.add_argument("--incidents", type=int, default=500, help="Target managed incident rows.")
    parser.add_argument("--skip-base-seed", action="store_true", help="Skip default seed.py run.")
    return parser


def seed_suppliers(target: int) -> int:
    inserted = 0
    existing = len(supplier_repository.list_supplier_records())
    next_index = existing + 1

    while existing + inserted < target:
        country = "USA" if next_index % 2 == 0 else "Spain"
        currency = "USD" if country == "USA" else "EUR"
        category = SUPPLIER_CATEGORIES[next_index % len(SUPPLIER_CATEGORIES)]

        supplier_repository.create_supplier_record(
            {
                "name": f"Perf Supplier {next_index:04d}",
                "country": country,
                "categories": [category],
                "rate_per_shipment": round(random.uniform(4.5, 18.5), 2),
                "currency": currency,
                "rate_updated_at": supplier_repository.current_timestamp(),
                "status": "active" if next_index % 7 else "suspended",
                "service_zone": f"Zone-{next_index % 12}",
                "contact_email": f"supplier{next_index}@perf.trackflow.test",
                "notes": "Generated by seed_performance_data.py",
            }
        )
        inserted += 1
        next_index += 1

    return inserted


def seed_inventory_products(session: Session, target: int) -> int:
    current = len(session.exec(select(SKU)).all())
    inserted = 0
    next_index = current + 1

    while current + inserted < target:
        warehouse = WAREHOUSES[next_index % len(WAREHOUSES)]
        category = CATEGORIES[next_index % len(CATEGORIES)]
        client = CLIENTS[next_index % len(CLIENTS)]
        sku_code = f"PERF-{category.value[:3].upper()}-{next_index:05d}"

        existing = session.exec(
            select(SKU).where(SKU.sku == sku_code, SKU.warehouse == warehouse)
        ).first()
        if existing is not None:
            next_index += 1
            continue

        session.add(
            SKU(
                name=f"{client} {category.value.title()} Item {next_index}",
                sku=sku_code,
                client_name=client,
                category=category,
                warehouse=warehouse,
            )
        )
        inserted += 1
        next_index += 1

    session.commit()
    return inserted


def seed_inventory_movements(session: Session, target: int) -> int:
    current_entries = len(session.exec(select(StockEntry)).all())
    current_exits = len(session.exec(select(StockExit)).all())
    current = current_entries + current_exits
    inserted = 0
    skus = session.exec(select(SKU)).all()

    if not skus:
        return 0

    movement_index = current + 1
    while current + inserted < target:
        sku = skus[movement_index % len(skus)]
        is_inbound = movement_index % 5 != 0

        if is_inbound:
            session.add(
                StockEntry(
                    sku_id=sku.id,
                    quantity=random.randint(5, 120),
                    reference=f"PERF-IN-{movement_index:06d}",
                    warehouse=sku.warehouse,
                    user_uuid="seed-performance",
                )
            )
        else:
            session.add(
                StockExit(
                    sku_id=sku.id,
                    quantity=random.randint(1, 8),
                    exit_type=ExitType.DISPATCH if movement_index % 2 == 0 else ExitType.LOSS,
                    tracking_number=f"TF-PERF-{movement_index:06d}" if movement_index % 2 == 0 else None,
                    warehouse=sku.warehouse,
                    user_uuid="seed-performance",
                )
            )

        inserted += 1
        movement_index += 1

        if inserted % 250 == 0:
            session.commit()

    session.commit()
    return inserted


def seed_managed_incidents(target: int) -> int:
    context = load_manager_context()
    existing = len(incident_repository.list_incident_records())
    inserted = 0
    next_index = existing + 1

    while existing + inserted < target:
        incident_repository.create_incident_record(
            {
                "title": f"Perf incident {next_index:04d}",
                "description": f"Synthetic incident for caching benchmark #{next_index}",
                "category": INCIDENT_CATEGORIES[next_index % len(INCIDENT_CATEGORIES)],
                "status": INCIDENT_STATUSES[next_index % len(INCIDENT_STATUSES)],
                "origin": INCIDENT_ORIGINS[next_index % len(INCIDENT_ORIGINS)],
                "branch": INCIDENT_BRANCHES[next_index % len(INCIDENT_BRANCHES)],
            }
        )
        inserted += 1
        next_index += 1

    _ = context
    return inserted


def run_performance_seed(
    *,
    products: int,
    movements: int,
    suppliers: int,
    incidents: int,
    skip_base_seed: bool,
) -> dict[str, int]:
    init_db()

    if not skip_base_seed:
        run_seed()

    supplier_inserted = seed_suppliers(suppliers)

    with Session(get_inventory_engine()) as session:
        product_inserted = seed_inventory_products(session, products)
        movement_inserted = seed_inventory_movements(session, movements)

    incident_inserted = seed_managed_incidents(incidents)

    return {
        "suppliers": supplier_inserted,
        "products": product_inserted,
        "movements": movement_inserted,
        "incidents": incident_inserted,
    }


def main() -> None:
    args = build_parser().parse_args()
    results = run_performance_seed(
        products=args.products,
        movements=args.movements,
        suppliers=args.suppliers,
        incidents=args.incidents,
        skip_base_seed=args.skip_base_seed,
    )
    print(
        "Performance seed complete. "
        f"Inserted suppliers={results['suppliers']}, "
        f"products={results['products']}, "
        f"movements={results['movements']}, "
        f"incidents={results['incidents']}."
    )


if __name__ == "__main__":
    main()
